#! /bin/sh

WS1="1 "
WS2="2 "
WS3="3 "
WS4="4 "

sxhkd &

xset -b
xset -dpms
xset s off
synclient TouchpadOff=1
udiskie -aNTF &
sudo iw dev wlp3s0 set power_save off
redshift &
xbanish &
compton -b &
feh --no-fehbg --bg-scale "$HOME/Images/background"

bspc monitor -d "$WS1" "$WS2" "$WS3" "$WS4"

bspc config border_width            1
bspc config window_gap              0
bspc config focus_follows_pointer   true

bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         true

bspc config normal_border_color     "#665c54"
bspc config active_border_color     "#00FFFF"
bspc config focused_border_color    "#ebdbb2"
bspc config presel_feedback_color   "#3c3836"

bspc rule -a Firefox desktop='^2' border=off
bspc rule -a Chromium border=off
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a explorer.exe desktop='^4' state=floating

ash "$XDG_CONFIG_HOME/bspwm/lemonbar" &
